Add missing .stylelintrc
Running "stylelint:core" (stylelint) task
Warning: Running stylelint failed
Error: No configuration provided for
/home/jenkins/workspace/npm-node-6-jessie/modules/ext.pickle.console.css
    at module.exports
(/home/jenkins/workspace/npm-node-6-jessie/node_modules/grunt-stylelint/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at stylelint._fullExplorer.load.then.then.config
(/home/jenkins/workspace/npm-node-6-jessie/node_modules/grunt-stylelint/node_modules/stylelint/lib/getConfigForFile.js:39:13)
Use --force to continue.

Removed phplint and phpcs from gruntfile, because there fails, are
already in composer
and were the only extension using grunt

Change-Id: If8877f00f4cb31d8c82f39810be975b52fecd4a0